name: CI
on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - released

env:
  GCR_REGISTRY: eu.gcr.io/sml-gke-iac
  GCR_REPOSITORY: scalatimes

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get release or tag
        uses: tenhaus/get-release-or-tag@v2
        id: tag
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          project_id: sml-gke-iac
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
          token_format: "access_token"
      - name: Login to docker registry
        uses: "docker/login-action@v1"
        with:
          registry: "eu.gcr.io"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Build Docker image and push to GCR
        env:
          IMAGE_TAG: ${{ steps.tag.outputs.tag }}
        run: |
          docker build -t $GCR_REGISTRY/$GCR_REPOSITORY:$IMAGE_TAG .
          docker push $GCR_REGISTRY/$GCR_REPOSITORY:$IMAGE_TAG
          echo "... image has been built and pushed to $GCR_REGISTRY/$GCR_REPOSITORY:$IMAGE_TAG"
